#!/bin/sh
### BEGIN INIT INFO
### run pppd and gpio at begining 
### END INIT INFO

start()
{
# echo "SETUPING startX...."
# startx -- -nocursor&
}

case "$1" in
  start)
    start
  ;;
  *)
  ;;
esac 
